public extension Artwork {
    static func sample(id: String) -> Artwork {
        Artwork(
            links: Links(linksSelf: nil, web: nil, search: nil),
            id: id,
            priref: nil,
            objectNumber: "123",
            language: "nl",
            title: "Title",
            copyrightHolder: nil,
            webImage: Image(guid: "", offsetPercentageX: 0, offsetPercentageY: 1, width: 100, height: 100, url: ""),
            colors: nil,
            colorsWithNormalization: nil,
            normalizedColors: nil,
            normalized32Colors: nil,
            materialsThesaurus: nil,
            techniquesThesaurus: nil,
            productionPlacesThesaurus: nil,
            titles: nil,
            description: nil,
            labelText: nil,
            objectTypes: nil,
            objectCollection: nil,
            makers: nil,
            principalMakers: nil,
            plaqueDescriptionDutch: nil,
            plaqueDescriptionEnglish: nil,
            principalMaker: nil,
            artistRole: nil,
            associations: nil,
            acquisition: nil,
            exhibitions: nil,
            materials: nil,
            techniques: nil,
            productionPlaces: nil,
            dating: nil,
            classification: nil,
            hasImage: true,
            historicalPersons: nil,
            inscriptions: nil,
            documentation: nil,
            catRefRPK: nil,
            principalOrFirstMaker: "M.E. The painter",
            dimensions: nil,
            physicalProperties: nil,
            physicalMedium: nil,
            longTitle: "Cool painting of M.E. The painter",
            subTitle: nil,
            scLabelLine: nil,
            label: nil,
            showImage: true,
            location: nil,
            permitDownload: true,
            headerImage: Image(guid: "", offsetPercentageX: 0, offsetPercentageY: 1, width: 100, height: 100, url: "https://example.com/example.jpg")
        )
    }
}

